### ISSUE TITLE
golang1.15 build error : misplaced compiler directive

### ISSUE THREAD

**Issue by bohehe** [GitbookIO/syncgroup#6]
Hi, I just got this error when I'm running CI with golang1.15 :
```
/go/pkg/mod/github.com/!gitbook!i!o/syncgroup@v0.0.0-20181003125046-3e73b2e6a972/quickhash/strhash.go:8:3: misplaced compiler directive
```
seems this kind of grammar is not allowed on golang1.15
```golang
//go:noescape
//go:linkname useAeshash runtime.useAeshash
var useAeshash bool
```

**Comment by AaronO** [comment]
@bohehe Go 1.15 causes multiple breaking changes for this repo, specifically `quickhash` which is in essence very similar to the newly added [hash/maphash](https://golang.org/pkg/hash/maphash/) pkg.

The main downside of `hash/maphash` is that it's not "deterministic" and the code `quickhash` relied on in `runtime`'s (ASM) Go internals has changed, such that it's no longer possible to build a deterministic hash func on top because it seeds a unique per-process key so the outputs of hashes vary between processes.

The public code in this module could easily be switched over to `maphash` since the lifecycles of hashes never exceed the process (aren't persisted to disk, etc...). So I'll probably update it to do that.

However, I was using `quickhash` as a fast hash function in some private projects that require persistence, so I'll have to figure out a solution there.

**Comment by AaronO** [comment]
For anyone else reading this, the main breaking issue are due to
- https://github.com/golang/go/blob/dbde566219336e84360b4a38da10b5f63b19021e/src/runtime/asm_amd64.s#L922
- https://github.com/golang/go/blob/dbde566219336e84360b4a38da10b5f63b19021e/src/runtime/alg.go#L342

The per-process key that is mixed into all AES backed hashes and is not a parameter (we can't pass in our own fixed key to get deterministic hashes).

**Comment by AaronO** [comment]
@bohehe `master` and the latest `0.3.0` tagged release should now be compatible with Go 1.15

**Comment by bohehe** [comment]
@AaronO Cool~ Thank you!!
